### ISSUE TITLE
checkBalances "could not detect network"

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/axelar-local-gmp-examples#23]
On a fresh install after running setup `npm run build` I try `node scripts/checkBalances` and get
```
node scripts/checkBalances.js
/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/logger/lib/index.js:233
        var error = new Error(message);
                    ^

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at JsonRpcProvider.<anonymous> (/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:561:54)
    at step (/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/gus/Documents/axelar/git-repos/axelar-local-gmp-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

Node.js v17.8.0
```

**Comment by ggutoski** [comment]
Fixed as of today.
