### ISSUE TITLE
Can't run hello world program

### ISSUE THREAD

**Issue by ShubhzDev** [axelarnetwork/axelar-local-gmp-examples#44]
D:\BlockChainProjects\axelar-local-gmp-examples> node scripts/createLocal
D:\BlockChainProjects\axelar-local-gmp-examples\node_modules\@ethersproject\bytes\lib\index.js:9
    return !!(value.toHexString);
                    ^

TypeError: Cannot read properties of undefined (reading 'toHexString')
    at isHexable (D:\BlockChainProjects\axelar-local-gmp-examples\node_modules\@ethersproject\bytes\lib\index.js:9:21)
    at hexlify (D:\BlockChainProjects\axelar-local-gmp-examples\node_modules\@ethersproject\bytes\lib\index.js:175:9)
    at new SigningKey (D:\BlockChainProjects\axelar-local-gmp-examples\node_modules\@ethersproject\signing-key\lib\index.js:20:82)
    at new Wallet (D:\BlockChainProjects\axelar-local-gmp-examples\node_modules\@ethersproject\wallet\lib\index.js:120:36)
    at Object.<anonymous> (D:\BlockChainProjects\axelar-local-gmp-examples\scripts\createLocal.js:26:30)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

**Comment by ShubhzDev** [comment]
cp .env.example .env
and set your private keys of wallet in .env file.
